using cuda
Traceback (most recent call last):
  File "train.py", line 251, in <module>
    main(params)
  File "train.py", line 207, in main
    model.cuda()
  File "/home/abhinav.ayalur/.conda/envs/285/lib/python3.7/site-packages/torch/nn/modules/module.py", line 463, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/home/abhinav.ayalur/.conda/envs/285/lib/python3.7/site-packages/torch/nn/modules/module.py", line 359, in _apply
    module._apply(fn)
  File "/home/abhinav.ayalur/.conda/envs/285/lib/python3.7/site-packages/torch/nn/modules/module.py", line 359, in _apply
    module._apply(fn)
  File "/home/abhinav.ayalur/.conda/envs/285/lib/python3.7/site-packages/torch/nn/modules/module.py", line 381, in _apply
    param_applied = fn(param)
  File "/home/abhinav.ayalur/.conda/envs/285/lib/python3.7/site-packages/torch/nn/modules/module.py", line 463, in <lambda>
    return self._apply(lambda t: t.cuda(device))
RuntimeError: CUDA error: out of memory
using cuda
Traceback (most recent call last):
  File "train.py", line 251, in <module>
    main(params)
  File "train.py", line 207, in main
    model.cuda()
  File "/home/abhinav.ayalur/.conda/envs/285/lib/python3.7/site-packages/torch/nn/modules/module.py", line 463, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/home/abhinav.ayalur/.conda/envs/285/lib/python3.7/site-packages/torch/nn/modules/module.py", line 359, in _apply
    module._apply(fn)
  File "/home/abhinav.ayalur/.conda/envs/285/lib/python3.7/site-packages/torch/nn/modules/module.py", line 359, in _apply
    module._apply(fn)
  File "/home/abhinav.ayalur/.conda/envs/285/lib/python3.7/site-packages/torch/nn/modules/module.py", line 381, in _apply
    param_applied = fn(param)
  File "/home/abhinav.ayalur/.conda/envs/285/lib/python3.7/site-packages/torch/nn/modules/module.py", line 463, in <lambda>
    return self._apply(lambda t: t.cuda(device))
RuntimeError: CUDA error: out of memory
using cuda
Traceback (most recent call last):
  File "train.py", line 251, in <module>
    main(params)
  File "train.py", line 207, in main
    model.cuda()
  File "/home/abhinav.ayalur/.conda/envs/285/lib/python3.7/site-packages/torch/nn/modules/module.py", line 463, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/home/abhinav.ayalur/.conda/envs/285/lib/python3.7/site-packages/torch/nn/modules/module.py", line 359, in _apply
    module._apply(fn)
  File "/home/abhinav.ayalur/.conda/envs/285/lib/python3.7/site-packages/torch/nn/modules/module.py", line 359, in _apply
    module._apply(fn)
  File "/home/abhinav.ayalur/.conda/envs/285/lib/python3.7/site-packages/torch/nn/modules/module.py", line 381, in _apply
    param_applied = fn(param)
  File "/home/abhinav.ayalur/.conda/envs/285/lib/python3.7/site-packages/torch/nn/modules/module.py", line 463, in <lambda>
    return self._apply(lambda t: t.cuda(device))
RuntimeError: CUDA error: out of memory
using cuda
Traceback (most recent call last):
  File "train.py", line 251, in <module>
    main(params)
  File "train.py", line 207, in main
    model.cuda()
  File "/home/abhinav.ayalur/.conda/envs/285/lib/python3.7/site-packages/torch/nn/modules/module.py", line 463, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/home/abhinav.ayalur/.conda/envs/285/lib/python3.7/site-packages/torch/nn/modules/module.py", line 359, in _apply
    module._apply(fn)
  File "/home/abhinav.ayalur/.conda/envs/285/lib/python3.7/site-packages/torch/nn/modules/module.py", line 359, in _apply
    module._apply(fn)
  File "/home/abhinav.ayalur/.conda/envs/285/lib/python3.7/site-packages/torch/nn/modules/module.py", line 381, in _apply
    param_applied = fn(param)
  File "/home/abhinav.ayalur/.conda/envs/285/lib/python3.7/site-packages/torch/nn/modules/module.py", line 463, in <lambda>
    return self._apply(lambda t: t.cuda(device))
RuntimeError: CUDA error: out of memory
using cuda
Traceback (most recent call last):
  File "train.py", line 251, in <module>
    main(params)
  File "train.py", line 207, in main
    model.cuda()
  File "/home/abhinav.ayalur/.conda/envs/285/lib/python3.7/site-packages/torch/nn/modules/module.py", line 463, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/home/abhinav.ayalur/.conda/envs/285/lib/python3.7/site-packages/torch/nn/modules/module.py", line 359, in _apply
    module._apply(fn)
  File "/home/abhinav.ayalur/.conda/envs/285/lib/python3.7/site-packages/torch/nn/modules/module.py", line 359, in _apply
    module._apply(fn)
  File "/home/abhinav.ayalur/.conda/envs/285/lib/python3.7/site-packages/torch/nn/modules/module.py", line 381, in _apply
    param_applied = fn(param)
  File "/home/abhinav.ayalur/.conda/envs/285/lib/python3.7/site-packages/torch/nn/modules/module.py", line 463, in <lambda>
    return self._apply(lambda t: t.cuda(device))
RuntimeError: CUDA error: out of memory
using cuda
Traceback (most recent call last):
  File "train.py", line 251, in <module>
    main(params)
  File "train.py", line 207, in main
    model.cuda()
  File "/home/abhinav.ayalur/.conda/envs/285/lib/python3.7/site-packages/torch/nn/modules/module.py", line 463, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/home/abhinav.ayalur/.conda/envs/285/lib/python3.7/site-packages/torch/nn/modules/module.py", line 359, in _apply
    module._apply(fn)
  File "/home/abhinav.ayalur/.conda/envs/285/lib/python3.7/site-packages/torch/nn/modules/module.py", line 359, in _apply
    module._apply(fn)
  File "/home/abhinav.ayalur/.conda/envs/285/lib/python3.7/site-packages/torch/nn/modules/module.py", line 381, in _apply
    param_applied = fn(param)
  File "/home/abhinav.ayalur/.conda/envs/285/lib/python3.7/site-packages/torch/nn/modules/module.py", line 463, in <lambda>
    return self._apply(lambda t: t.cuda(device))
RuntimeError: CUDA error: out of memory
using cuda
Traceback (most recent call last):
  File "train.py", line 251, in <module>
    main(params)
  File "train.py", line 207, in main
    model.cuda()
  File "/home/abhinav.ayalur/.conda/envs/285/lib/python3.7/site-packages/torch/nn/modules/module.py", line 463, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/home/abhinav.ayalur/.conda/envs/285/lib/python3.7/site-packages/torch/nn/modules/module.py", line 359, in _apply
    module._apply(fn)
  File "/home/abhinav.ayalur/.conda/envs/285/lib/python3.7/site-packages/torch/nn/modules/module.py", line 359, in _apply
    module._apply(fn)
  File "/home/abhinav.ayalur/.conda/envs/285/lib/python3.7/site-packages/torch/nn/modules/module.py", line 381, in _apply
    param_applied = fn(param)
  File "/home/abhinav.ayalur/.conda/envs/285/lib/python3.7/site-packages/torch/nn/modules/module.py", line 463, in <lambda>
    return self._apply(lambda t: t.cuda(device))
RuntimeError: CUDA error: out of memory
using cuda
Traceback (most recent call last):
  File "train.py", line 251, in <module>
    main(params)
  File "train.py", line 207, in main
    model.cuda()
  File "/home/abhinav.ayalur/.conda/envs/285/lib/python3.7/site-packages/torch/nn/modules/module.py", line 463, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/home/abhinav.ayalur/.conda/envs/285/lib/python3.7/site-packages/torch/nn/modules/module.py", line 359, in _apply
    module._apply(fn)
  File "/home/abhinav.ayalur/.conda/envs/285/lib/python3.7/site-packages/torch/nn/modules/module.py", line 359, in _apply
    module._apply(fn)
  File "/home/abhinav.ayalur/.conda/envs/285/lib/python3.7/site-packages/torch/nn/modules/module.py", line 381, in _apply
    param_applied = fn(param)
  File "/home/abhinav.ayalur/.conda/envs/285/lib/python3.7/site-packages/torch/nn/modules/module.py", line 463, in <lambda>
    return self._apply(lambda t: t.cuda(device))
RuntimeError: CUDA error: out of memory
using cuda
Traceback (most recent call last):
  File "train.py", line 251, in <module>
    main(params)
  File "train.py", line 207, in main
    model.cuda()
  File "/home/abhinav.ayalur/.conda/envs/285/lib/python3.7/site-packages/torch/nn/modules/module.py", line 463, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/home/abhinav.ayalur/.conda/envs/285/lib/python3.7/site-packages/torch/nn/modules/module.py", line 359, in _apply
    module._apply(fn)
  File "/home/abhinav.ayalur/.conda/envs/285/lib/python3.7/site-packages/torch/nn/modules/module.py", line 359, in _apply
    module._apply(fn)
  File "/home/abhinav.ayalur/.conda/envs/285/lib/python3.7/site-packages/torch/nn/modules/module.py", line 381, in _apply
    param_applied = fn(param)
  File "/home/abhinav.ayalur/.conda/envs/285/lib/python3.7/site-packages/torch/nn/modules/module.py", line 463, in <lambda>
    return self._apply(lambda t: t.cuda(device))
RuntimeError: CUDA error: out of memory
